version: '3.8'

services:
  # Nginx sebagai web server
  nginx:
    image: nginx:alpine
    container_name: waserba_nginx
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waserba_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
    networks:
      - laravel
    command: >
      sh -c "composer install --no-dev --optimize-autoloader &&
             php artisan key:generate --force &&
             php artisan migrate --force &&
             php-fpm"

  # MySQL Database
  mysql:
    image: mysql:8
    container_name: waserba_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: laradminlte
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: "laravel123"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata: