version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:80"  # Format: HOST_PORT:CONTAINER_PORT
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: user_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/DatabaseKoperasi.sql:/docker-entrypoint-initdb.d/DatabaseKoperasi.sql

    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge