version: '3.8'

services:
    # Service aplikasi Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: always
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - app-network

    # Service Nginx
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        ports:
            - "9001:443" # Port 9001 untuk HTTPS
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/certs/:/etc/nginx/certs/
        depends_on:
            - app
        networks:
            - app-network

    # Service database MySQL
    db:
        image: mysql:8.0
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: 'laradminlte' # Sesuai dengan .env.example
            MYSQL_USER: 'laraveluser' # Sesuai dengan .env.example
            MYSQL_PASSWORD: 'laravel123' # Sesuai dengan .env.example
            MYSQL_ROOT_PASSWORD: 'passwordroot'
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

volumes:
    dbdata:

networks:
    app-network:
        driver: bridge